services:
  backend:
    build: ./Backend
    container_name: jobPortal-server
    ports: 
      - "5000:4000"
    networks:
      - jobPortal-network
    env_file:
      - ./Backend/.env
    restart: unless-stopped
  frontend:
    build: ./Frontend
    container_name: jobPortal-client
    ports:
      - "5173:3000"
    networks:
      - jobPortal-network
    depends_on:
      - backend
    env_file:
      - ./Frontend/.env
    restart: unless-stopped

networks:
  jobPortal-network:
    driver: bridge